= JavaFX
Andres Almiray
:jbake-type: page
:jbake-status: published
:linkattrs:
:icons:         font
:project-owner: kordamp

== BootstrapFX

:project-name:  bootstrapfx
:project-group: org.kordamp.bootstrapfx

image:https://img.shields.io/badge/license-MIT-blue.svg["MIT Licensed", link="https://opensource.org/licenses/MIT"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

Bootstrap for JavaFX.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== DesktopPaneFX

:project-name:  desktoppanefx
:project-group: org.kordamp.desktoppanefx

image:https://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="https://spdx.org/licenses/Apache-2.0.html"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

DesktopPaneFX is a JavaFX version of Swing’s JDesktopPane which can be used as a container for individual "child" similar to JInternalFrames.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== HarmonicFX

:project-name:  harmonicfx
:project-group: org.kordamp.harmonicfx

image:https://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="https://spdx.org/licenses/Apache-2.0.html"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

A collection of link:https://harmoniccode.blogspot.ch/search/label/fridayfun[Friday Fun] JavaFX components authored by
link:https://twitter.com/hansolo_[@hansolo_].

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== Ikonli

:project-name:  ikonli
:project-group: org.kordamp.ikonli

image:https://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="https://spdx.org/licenses/Apache-2.0.html"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-core.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

Ikonli provides icon packs that can be used in Java applications. Currently Swing and JavaFX UI toolkits are supported.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== JSilhouette

:project-name:  jsilhouette
:project-group: org.kordamp.jsilhouette

image:https://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="https://spdx.org/licenses/Apache-2.0.html"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}-javafx.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

JSilhouette provides additional shapes for Java applications. Currently JavaFX is supported.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

