= Gradle
Andres Almiray
:jbake-type: page
:jbake-status: published
:linkattrs:
:icons:         font
:project-owner: kordamp
:project-repo:  maven

== Kordamp Gradle Plugins

:project-name: kordamp-gradle-plugins
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

This project provides a set of Gradle plugins that follow an opinionated way to build Java and Groovy projects.
The conventions define by these plugins closely follow common practices observed in many Open Source projects.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code] +
icon:book[]  link:http://kordamp.org/{project-name}/[Guide]

== Kordamp Gradle Project Template

:project-name: kordamp-gradle-project-template
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

A Layzbones project template for projects configured with Kordamp plugins.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== Jandex Gradle Plugin

:project-name: jandex-gradle-plugin
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

Gradle plugin for link:https://github.com/wildfly/jandex[Jandex], a space efficient Java annotation indexer and offline reflection library.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== JDeps Gradle Plugin

:project-name: jdeps-gradle-plugin
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

Runs the `jdeps` command on the project’s output and all of its dependencies.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== JDeprscan Gradle Plugin

:project-name: jdeprscan-gradle-plugin
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

Runs the `jdeprscan` command on the project’s output.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== Markdown Gradle Plugin

:project-name: markdown-gradle-plugin
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

This plugin provides a facility for converting markdown into HTML, as well as converting HTML back into markdown.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== OCI Gradle Plugin

:project-name: oci-gradle-plugin
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

A Gradle plugin for the link:https://github.com/oracle/oci-java-sdk[Java SDK for Oracle Cloud Infrastructure].

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code] +
icon:book[]  link:http://kordamp.org/{project-name}/[Guide]

== OCI Gradle Build Cache Plugin

:project-name: oci-gradle-build-cache-plugin
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

This is a custom Gradle link:https://docs.gradle.org/current/userguide/build_cache.html[build cache] implementation which uses
the link:https://www.oracle.com/cloud/[Oracle Cloud] to store the cache objects.

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code]

== yGuard Gradle Plugin

:project-name: yguard-gradle-plugin
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]

Gradle plugin for obfuscating Java code with link:https://www.yworks.com/products/yguard[yGuard].

icon:github[] link:https://github.com/{project-owner}/{project-name}/[Code] +
icon:book[]  link:http://kordamp.org/{project-name}/[Guide]

